### ISSUE TITLE
ssh problems while vagrant up

### ISSUE THREAD

**Issue by ssmoliarchuk** [adamaig/dev-with-docker-on-ubuntu#1]
Hi. It was a problem on OS X El Capitan 10.11.6 with ssh while `vagrant up`.
I fixed it by enter the following command in terminal window:
`ssh-keygen -t rsa`
and replace 
`{ s: "~#{USERNAME}/.ssh/config", d: "/tmp/ssh_config" },` on `{ s: "/private/etc/ssh/ssh_config", d: "/tmp/ssh_config" },` in Vagrantfile
Now all is ok

**Comment by adamaig** [comment]
@SergeySmile The change you made looks like it will copy the system ssh config, and end up using it for the individual user. That may not be what you want, but I'm glad it solved your issue.

Note that there was an error in the Vagrantfile where the ssh config was being copied into the vagrant user's setup, but the latest commits fix that.

**Comment by ssmoliarchuk** [comment]
Ok, thx. Will try updated version.

**Comment by adamaig** [comment]
@SergeySmile I just realized the issue was that the vagrant user wasn't added to the docker group. If you're not using the vagrant user, please run `sudo usermod -aG docker username` to fix things. If you're using the same user as your OSX account, the user is added to the docker group on line 138 of the Vagrantfile.
